INFO     viperlog:parameter.py:227 Module path: [38;2;50;50;205m/home/runner/work/testviper/testviper/src/toolviper[0m
WARNING  viperlog:logger.py:109 It is recommended that the local cache directory be set using the [38;2;50;50;205mdask_local_dir[0m parameter.
INFO     distributed.scheduler:scheduler.py:8182 Registering Worker plugin worker_logger
INFO     viperlog:logger.py:55 Client <MenrvaClient: 'tcp://127.0.0.1:33445' processes=2 threads=2, memory=5.59 GiB>
INFO     viperlog:logger.py:55 Downloading from [cloudflare] ....
ERROR    viperlog:logger.py:122 [[38;2;220;20;60mdownload[0m]: Requested file not found: 59755_eq_interleave_15.ms
INFO     viperlog:logger.py:55 For a list of available files try using [38;2;50;50;205mtoolviper.utils.data.list_files()[0m.
INFO     viperlog:logger.py:55 Trying to retrieve missing files dropbox: ['59755_eq_interleave_15.ms']
WARNING  viperlog:logger.py:109 File exists: [38;2;50;50;205m/home/runner/work/testviper/testviper/src/toolviper/src/toolviper/utils/data/.dropbox[0m
INFO     viperlog:logger.py:55 Updating file metadata information ... 
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID']
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID']
INFO     viperlog:logger.py:55 Number of partitions: 1
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [0 1], SCAN [0 1 2 3]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0 0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 Downloading from [cloudflare] ....
INFO     viperlog:logger.py:55 File exists: /tmp/test/59755_eq_interleave_15.ms
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID', 'FIELD_ID']
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID', 'FIELD_ID']
INFO     viperlog:logger.py:55 Number of partitions: 2
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [0], SCAN [0 2]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [1], SCAN [1 3]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.