INFO     viperlog:parameter.py:212 Module path: [38;2;50;50;205m/home/runner/work/testviper/testviper/external/toolviper/src/toolviper[0m
WARNING  viperlog:logger.py:109 It is recommended that the local cache directory be set using the [38;2;50;50;205mdask_local_dir[0m parameter.
INFO     distributed.scheduler:scheduler.py:8182 Registering Worker plugin worker_logger
INFO     viperlog:logger.py:55 Client <MenrvaClient: 'tcp://127.0.0.1:35135' processes=2 threads=2, memory=5.59 GiB>
INFO     viperlog:parameter.py:212 Module path: [38;2;50;50;205m/home/runner/work/testviper/testviper/external/toolviper/src/toolviper[0m
INFO     viperlog:logger.py:55 Downloading from [cloudflare] ....
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID']
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID']
INFO     viperlog:logger.py:55 Number of partitions: 1
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [0 1 2 3 4 5 6 7], SCAN [0 1 2 3 4 5 6 7]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0 0 0 0 0 0 0 0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:parameter.py:212 Module path: [38;2;50;50;205m/home/runner/work/testviper/testviper/external/toolviper/src/toolviper[0m
INFO     viperlog:logger.py:55 Downloading from [cloudflare] ....
INFO     viperlog:logger.py:55 File exists: /tmp/test/59749_bp_8beams_pattern.ms
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID', 'FIELD_ID']
INFO     viperlog:logger.py:55 Partition scheme that will be used: ['DATA_DESC_ID', 'OBSERVATION_ID', 'FIELD_ID']
INFO     viperlog:logger.py:55 Number of partitions: 8
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [0], SCAN [0]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [1], SCAN [1]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [2], SCAN [2]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [3], SCAN [3]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [4], SCAN [4]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [5], SCAN [5]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [6], SCAN [6]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.
INFO     viperlog:logger.py:55 OBSERVATION_ID [0], DDI [0], STATE [-1], FIELD [7], SCAN [7]
WARNING  viperlog:logger.py:109 Could not find SOURCE table for source_id [0]. Source information will not be included in the field_and_source_xds.