WARNING  viperlog:logger.py:109 File exists: [38;2;50;50;205m/home/runner/work/testviper/testviper/src/toolviper/src/toolviper/utils/data/.dropbox[0m
INFO     viperlog:logger.py:55 Updating file metadata information ...