{"uid":"16743502f4e7e349","name":"test_summary_empty","fullName":"tests.unit.measurement_set.test_processing_set_xdt.TestProcessingSetXdtErrors#test_summary_empty","historyId":"7f43d11dca99d6518d4939a4e3852abc","time":{"start":1752002160729,"stop":1752002160730,"duration":1},"description":"Test that summary raises an exception on empty DataTree","descriptionHtml":"<p>Test that summary raises an exception on empty DataTree</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"parentSuite","value":"tests.unit.measurement_set"},{"name":"suite","value":"test_processing_set_xdt"},{"name":"subSuite","value":"TestProcessingSetXdtErrors"},{"name":"host","value":"fv-az1788-284"},{"name":"thread","value":"2981-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.unit.measurement_set.test_processing_set_xdt"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":[]},"source":"16743502f4e7e349.json","parameterValues":[]}