{"name": "test_version_fallback_unknown_when_no_dunder", "status": "passed", "description": "If both metadata lookup and __version__ access fail, version should be 'unknown'.", "start": 1757016872115, "stop": 1757016872134, "uuid": "3bc04436-4548-49b7-8cbc-d9dff49900d2", "historyId": "fd71e3a9dcb911ab0e6ce1dae999834f", "testCaseId": "fd71e3a9dcb911ab0e6ce1dae999834f", "fullName": "tests.unit.distributed.image_analysis.test_multi_gaussian2d_fit.TestResultMetadataVersion#test_version_fallback_unknown_when_no_dunder", "labels": [{"name": "parentSuite", "value": "tests.unit.distributed.image_analysis"}, {"name": "suite", "value": "test_multi_gaussian2d_fit"}, {"name": "subSuite", "value": "TestResultMetadataVersion"}, {"name": "host", "value": "pkrvm7jw40e0xgp"}, {"name": "thread", "value": "4072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.distributed.image_analysis.test_multi_gaussian2d_fit"}], "titlePath": ["tests", "unit", "distributed", "image_analysis", "test_multi_gaussian2d_fit.py", "TestResultMetadataVersion"]}