{"name": "test_curve_fit_exception_sets_failure", "status": "passed", "start": 1757016870550, "stop": 1757016870552, "uuid": "b9bd6478-621d-4eea-a9b4-927a8ebe92a3", "historyId": "e6a2074ce40a53b1b4f7f85ccbc1437c", "testCaseId": "e6a2074ce40a53b1b4f7f85ccbc1437c", "fullName": "tests.unit.distributed.image_analysis.test_multi_gaussian2d_fit.TestOptimizerFailures#test_curve_fit_exception_sets_failure", "labels": [{"name": "parentSuite", "value": "tests.unit.distributed.image_analysis"}, {"name": "suite", "value": "test_multi_gaussian2d_fit"}, {"name": "subSuite", "value": "TestOptimizerFailures"}, {"name": "host", "value": "pkrvm7jw40e0xgp"}, {"name": "thread", "value": "4072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.distributed.image_analysis.test_multi_gaussian2d_fit"}], "titlePath": ["tests", "unit", "distributed", "image_analysis", "test_multi_gaussian2d_fit.py", "TestOptimizerFailures"]}