ERROR    viperlog:logger.py:122 [[38;2;220;20;60mopen_json[0m]: tests/data/test.json doesn't exist ... exiting.
INFO     viperlog:logger.py:55 Function open_json(...) working as expected.